# Website name
title: Jacob Varner's Book Log

# Website description
description: >-
  Book reviews, ratings, and recommendations based on my reading list, the
  topics I enjoy, and the books that I think others should read.

baseurl: "/"
url: "https://books.jacobvarner.com"

# Number of posts per page and url/slug used for pagination
paginate: 10
paginate_path: "/page:num/"

# Sets the Sass output style (nested, expanded, compact, compressed)
sass:
  style: compressed

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
